import {afterNextRender, Component, ElementRef, inject, Injector, Input, OnInit, ViewEncapsulation} from '@angular/core';
import {
    AlertController, IonButton, IonButtons, IonContent, IonHeader, IonIcon, IonNote, IonSpinner, IonTitle, IonToolbar, ModalController,
} from '@ionic/angular/standalone';
import {addIcons} from 'ionicons';
import {playOutline} from 'ionicons/icons';
import {Lecture, ManService} from '../../man.service';
import {markedWithMath, renderMath} from './markdown-math';

// Matches a leading YAML frontmatter block: `---` ... `---` at the very start of the document.
const FRONTMATTER = /^\uFEFF?---[ \t]*\r?\n[\s\S]*?\r?\n(?:---|\.\.\.)[ \t]*(?:\r?\n|$)/;

export interface DocHeading {
    index: number; // position among the rendered h1-h3 elements
    text: string;
    level: number;
}

export function stripFrontmatter(markdown: string): string {
    return markdown.replace(FRONTMATTER, '');
}

const unquote =(value: string | undefined) => value?.trim().replace(/^(["'])(.*)\1$/, '$2') || null;

// Reads the AI model names from the frontmatter without a full YAML parser (only two simple scalar fields are needed).
export function extractModels(markdown: string): {transcription: string | null, article: string | null} {
    const lines = (markdown.match(FRONTMATTER)?.[0] ?? '').split(/\r?\n/);
    let article: string | null = null;
    const transcription: string[] = [];
    let inTranscription = false;
    let inModelList = false;
    // Scanned line by line: a single regex over the whole block overflows Firefox's regex stack on long frontmatter.
    for (const line of lines) {
        if (/^\S/.test(line)) {
            inTranscription = /^transcription:[ \t]*$/.test(line);
            inModelList = false;
            article ??= unquote(line.match(/^article_model:[ \t]*(.+?)[ \t]*$/)?.[1]);
        } else if (inTranscription) {
            const model = line.match(/^[ \t]+model:[ \t]*(.*?)[ \t]*$/);
            const item = line.match(/^[ \t]+-[ \t]+(.+?)[ \t]*$/);
            if (model) {
                inModelList = !model[1];
                const value = unquote(model[1]);
                if (value) {
                    transcription.push(value);
                }
            } else if (inModelList && item) {
                transcription.push(unquote(item[1]) ?? '');
            } else {
                inModelList = false;
            }
        }
    }
    return {transcription: transcription.filter(Boolean).join(', ') || null, article};
}

// Loosely compares heading texts, ignoring case, punctuation and the Markdown formatting lost when rendering.
const normalizeHeading = (text: string) => text.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '');

// Resolves true only if the user explicitly accepts the AI disclaimer (or accepted it within the last 7 days
// and ticked "don't show again").
export async function confirmAiDisclaimer(alertController: AlertController): Promise<boolean> {
    const storageKey = 'aiDocDisclaimerAcceptedAt';
    try {
        const acceptedAt = Number(localStorage.getItem(storageKey));
        if (acceptedAt && Date.now() - acceptedAt < 7 * 24 * 60 * 60 * 1000) {
            return true;
        }
    } catch {
        // Storage unavailable; just ask again
    }
    const alert = await alertController.create({
        header: 'AI-generated content',
        message: 'This document is generated by AI from the lecture recording. ' +
            'This feature is intended only to assist with content mapping and searching, ' +
            'not as a source of study material or a replacement for the lecture and official course materials. ' +
            'AI can make mistakes, so please verify important information before relying on it.',
        backdropDismiss: false,
        inputs: [
            {type: 'checkbox', label: "Don't show this again for 7 days", value: 'skip', checked: false},
        ],
        buttons: [
            {text: 'Cancel', role: 'cancel'},
            {text: 'I understand and accept', role: 'confirm'},
        ],
    });
    await alert.present();
    const {role, data} = await alert.onDidDismiss();
    if (role !== 'confirm') {
        return false;
    }
    if (data?.values?.includes('skip')) {
        try {
            localStorage.setItem(storageKey, String(Date.now()));
        } catch {
            // Storage unavailable; the user will be asked again next time
        }
    }
    return true;
}

@Component({
    selector: 'app-modal-document',
    templateUrl: 'modal-document.component.html',
    styleUrls: ['modal-document.component.scss'],
    // [innerHTML] content doesn't get Angular's scoping attributes, so scoped styles would never match it
    encapsulation: ViewEncapsulation.None,
    imports: [IonButton, IonButtons, IonContent, IonHeader, IonIcon, IonNote, IonSpinner, IonTitle, IonToolbar],
})
export class ModalDocumentComponent implements OnInit {
    private manService = inject(ManService);
    private modalCtrl = inject(ModalController);
    private host = inject<ElementRef<HTMLElement>>(ElementRef);
    private injector = inject(Injector);

    @Input() video: Pick<Lecture, 'id' | 'title' | 'lecturer'>;
    // Section to scroll to once loaded, as `Title > Heading > Subheading` (from a search hit).
    @Input() headingPath?: string;
    // Shows a button that dismisses the modal with the `watch` role, for when it is opened outside the player.
    @Input() showWatchButton = false;

    constructor() {
        addIcons({playOutline});
    }

    loading = true;
    error = false;
    // Angular's [innerHTML] sanitizes this before rendering.
    html = '';
    models: {transcription: string | null, article: string | null} = {transcription: null, article: null};
    headings: DocHeading[] = [];
    activeHeading = -1;

    ngOnInit() {
        this.manService.getVideo(String(this.video.id)).subscribe({
            next: info => {
                const document = info?.document?.trim();
                if (document) {
                    this.models = extractModels(document);
                    ({html: this.html, headings: this.headings} = this.addHeadingIds(
                        markedWithMath.parse(stripFrontmatter(document), {async: false}),
                    ));
                    const target = this.findHeading(this.headingPath);
                    // Set before rendering: changing it in the render callback below would trip Angular's
                    // ExpressionChangedAfterItHasBeenChecked check.
                    this.activeHeading = target ?? (this.headings.length ? 0 : -1);
                    // The math placeholders only exist in the DOM once the sanitized HTML has been rendered.
                    afterNextRender(() => {
                        renderMath(this.host.nativeElement);
                        if (target !== null) {
                            this.scrollWhenShown(target);
                        }
                    }, {injector: this.injector});
                }
                this.loading = false;
            },
            error: () => {
                this.error = true;
                this.loading = false;
            },
        });
    }

    // Collect h1-h3 for the outline. The sanitizer strips id attributes, so headings are looked up by index later.
    private addHeadingIds(html: string): {html: string, headings: DocHeading[]} {
        const doc = new DOMParser().parseFromString(html, 'text/html');
        const headings: DocHeading[] = [];
        doc.body.querySelectorAll('h1, h2, h3').forEach((el, index) => {
            headings.push({index, text: el.textContent?.trim() ?? '', level: Number(el.tagName[1])});
        });
        return {html: doc.body.innerHTML, headings};
    }

    // Index of the deepest heading of `headingPath` found in the outline, or null.
    private findHeading(headingPath?: string): number | null {
        const segments = (headingPath ?? '').split(' > ').map(normalizeHeading).filter(Boolean);
        for (const segment of segments.reverse()) {
            const heading = this.headings.find(h => normalizeHeading(h.text) === segment);
            if (heading) {
                return heading.index;
            }
        }
        return null;
    }

    // A fast response renders the document while the modal is still hidden, before it is presented, and scrolling
    // a hidden element does nothing. In that case scroll once the modal has been presented.
    private scrollWhenShown(index: number) {
        const scroll = () => this.renderedHeadings()[index]?.scrollIntoView({block: 'start'});
        const modal = this.host.nativeElement.closest('ion-modal');
        if (modal && !this.host.nativeElement.getClientRects().length) {
            modal.addEventListener('ionModalDidPresent', scroll, {once: true});
        } else {
            scroll();
        }
    }

    private renderedHeadings(): HTMLElement[] {
        return Array.from(this.host.nativeElement.querySelectorAll<HTMLElement>('.markdown-body :is(h1, h2, h3)'));
    }

    scrollTo(index: number) {
        this.activeHeading = index;
        this.renderedHeadings()[index]?.scrollIntoView({behavior: 'smooth', block: 'start'});
    }

    // Highlight the last heading that has scrolled past the top of the content area.
    onScroll(event: Event) {
        const top = (event.target as HTMLElement).getBoundingClientRect().top + 60;
        let active = this.headings.length ? 0 : -1;
        this.renderedHeadings().forEach((el, i) => {
            if (el.getBoundingClientRect().top <= top) {
                active = i;
            }
        });
        this.activeHeading = active;
    }

    close() {
        return this.modalCtrl.dismiss(null, 'cancel');
    }

    watch() {
        return this.modalCtrl.dismiss(null, 'watch');
    }
}
